version: '3.3'

volumes:
  db_volume:
  admin_static_volume:
  admin_media_volume:
  local_redis_data:

services:
  db:
    image: postgres:15.4
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - .envs/.db
    ports:
      - "5436:5432"

  admin:
    build:
      context: .
      dockerfile: ./compose/admin/Dockerfile
    depends_on:
      - db
    volumes:
      - admin_static_volume:/billing_manager/static
      - admin_media_volume:/billing_manager/media
    ports:
      - "8008:80"
    env_file:
      - .envs/.admin
    restart: on-failure

  redis:
    image: redis:6.0.1-alpine
    env_file:
      - .envs/.admin
    ports:
      - '6379:6379'
    volumes:
      - local_redis_data:/data
    command: >
      --maxclients 20000 --timeout 300 --appendonly yes --replica-read-only no
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always
