# Generated by Django 4.2.4 on 2024-11-25 13:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Price')),
                ('currency', models.CharField(choices=[('RUB', 'Rubl'), ('USD', 'Dollar'), ('EUR', 'EUR')], max_length=3, verbose_name='Currency')),
                ('is_subscription', models.BooleanField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
            ],
            options={
                'verbose_name': 'Payment Item',
                'verbose_name_plural': 'Payment Items',
            },
        ),
        migrations.CreateModel(
            name='PaymentItemsGroup',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
            ],
            options={
                'verbose_name': 'Payment Items Group',
                'verbose_name_plural': 'Payment Items Group',
            },
        ),
        migrations.CreateModel(
            name='PaymentItemDiscount',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('items_count', models.PositiveIntegerField(verbose_name='Items Count')),
                ('discount_value', models.PositiveIntegerField(verbose_name='Discount Value, %')),
                ('payment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentitem')),
            ],
            options={
                'verbose_name': 'Payment Item Discount',
                'verbose_name_plural': 'Payment Items Discounts',
            },
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentitemsgroup'),
        ),
    ]
