# Generated by Django 4.2.4 on 2024-11-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentitem',
            options={'verbose_name': 'Платежная позиция', 'verbose_name_plural': 'Платежные позиции'},
        ),
        migrations.AlterModelOptions(
            name='paymentitemdiscount',
            options={'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='paymentitemsgroup',
            options={'verbose_name': 'Группа платежных позиций', 'verbose_name_plural': 'Группа платежных позиций'},
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар'), ('EUR', 'Евро')], max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='paymentitemdiscount',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='paymentitemdiscount',
            name='discount_value',
            field=models.PositiveIntegerField(verbose_name='Скидка, %'),
        ),
        migrations.AlterField(
            model_name='paymentitemdiscount',
            name='items_count',
            field=models.PositiveIntegerField(verbose_name='Количество позиций'),
        ),
        migrations.AlterField(
            model_name='paymentitemdiscount',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='paymentitemsgroup',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='paymentitemsgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='paymentitemsgroup',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
