# Generated by Django 4.2.4 on 2024-11-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_system',
            field=models.IntegerField(choices=[(1, 'Dummy'), (2, 'ROBOKASSA'), (3, 'YKASSA')], default=1, verbose_name='Payment System'),
            preserve_default=False,
        ),
    ]
