# Generated by Django 4.2.4 on 2024-11-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_payment_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Приложение', 'verbose_name_plural': 'Приложения'},
        ),
        migrations.AlterModelOptions(
            name='applicationtoken',
            options={'verbose_name': 'Токен приложения', 'verbose_name_plural': 'Токены приложения'},
        ),
        migrations.AlterField(
            model_name='application',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_system',
            field=models.IntegerField(choices=[(1, 'Dummy'), (2, 'ROBOKASSA'), (3, 'YKASSA')], verbose_name='Платежная система'),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='applicationtoken',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='applicationtoken',
            name='salt',
            field=models.CharField(max_length=10, verbose_name='Соль'),
        ),
        migrations.AlterField(
            model_name='applicationtoken',
            name='token',
            field=models.CharField(max_length=200, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='applicationtoken',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
