# Generated by Django 4.2.4 on 2024-11-27 05:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSystemParamter',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('parameter_value', models.CharField(max_length=200, verbose_name='Parameter Value')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
            ],
            options={
                'verbose_name': 'Payment System Paramter',
                'verbose_name_plural': 'Payment System Paramtres',
            },
        ),
    ]
