# Generated by Django 4.2.4 on 2024-11-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_paymentsystemparamter'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystemparamter',
            name='payment_system',
            field=models.IntegerField(choices=[(1, 'Dummy'), (2, 'ROBOKASSA'), (3, 'YKASSA')], default=1, verbose_name='Платежная система'),
            preserve_default=False,
        ),
    ]
