# Generated by Django 4.2.4 on 2024-11-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_paymentsystemparamter_payment_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsystemparamter',
            name='parameter_value',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Parameter Value'),
        ),
    ]
