# Generated by Django 4.2.4 on 2025-06-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_paymentsystemparamter_parameter_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='callback_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Callback Url'),
        ),
    ]
