# Generated by Django 4.2.4 on 2025-07-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystemparamter',
            name='is_fiscalisation',
            field=models.BooleanField(default=False, verbose_name='Is Fiscalization'),
        ),
    ]
