# Generated by Django 4.2.4 on 2025-07-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_paymentsystemparamter_is_fiscalisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsystemparamter',
            name='is_fiscalisation',
        ),
        migrations.AddField(
            model_name='application',
            name='is_fiscalisation',
            field=models.BooleanField(default=False, verbose_name='Is Fiscalization'),
        ),
    ]
