# Generated by Django 4.2.4 on 2025-07-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_remove_paymentsystemparamter_is_fiscalisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sno',
            field=models.IntegerField(choices=[(1, 'Общая СН'), (2, 'Упрощенная СН (доходы)'), (3, 'Упрощенная СН (доходы минус расходы)'), (4, 'Единый сельскохозяйственный налог'), (5, 'Патентная СН')], default=None, null=True, verbose_name='Налогоблажение(Если включена фискализация)'),
        ),
        migrations.AddField(
            model_name='application',
            name='tax',
            field=models.IntegerField(choices=[(1, 'Без НДС'), (2, 'НДС по ставке 0%'), (3, 'НДС чека по ставке 10%'), (4, 'НДС чека по расчетной ставке 10/110'), (5, 'НДС чека по ставке 20%'), (7, 'НДС чека по расчетной ставке 20/120'), (8, 'НДС по ставке 5%'), (9, 'НДС по ставке 7%'), (10, 'НДС чека по расчетной ставке 5/105'), (11, 'НДС чека по расчетной ставке 7/107')], default=1, null=True, verbose_name='НДС(Если налогоблажение Общая СН)'),
        ),
    ]
