# Generated by Django 4.2.4 on 2026-02-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_application_payment_system_paygine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='callback_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Урл колбэка'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_fiscalisation',
            field=models.BooleanField(default=False, verbose_name='Фискализируется?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_system',
            field=models.IntegerField(choices=[(1, 'Dummy'), (2, 'ROBOKASSA'), (3, 'YKASSA'), (4, 'PAYGINE')], verbose_name='Платежная система'),
        ),
        migrations.AlterField(
            model_name='paymentsystemparamter',
            name='parameter_value',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Значение параметра'),
        ),
        migrations.AlterField(
            model_name='paymentsystemparamter',
            name='payment_system',
            field=models.IntegerField(choices=[(1, 'Dummy'), (2, 'ROBOKASSA'), (3, 'YKASSA'), (4, 'PAYGINE')], verbose_name='Платежная система'),
        ),
    ]
