# Generated by Django 4.2.4 on 2026-03-13 07:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_alter_application_callback_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта организации'),
        ),
        migrations.AddField(
            model_name='application',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИНН организации'),
        ),
        migrations.AddField(
            model_name='application',
            name='ofd_interface',
            field=models.IntegerField(blank=True, choices=[(1, 'ATOL')], null=True, verbose_name='OFD interface'),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место расчетов'),
        ),
        migrations.CreateModel(
            name='OFDInterfaceParamter',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('parameter_value', models.CharField(blank=True, max_length=200, null=True, verbose_name='Значение параметра')),
                ('ofd_interface', models.IntegerField(choices=[(1, 'ATOL')], verbose_name='OFD Interface')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
            ],
            options={
                'verbose_name': 'OFD Interface Paramter',
                'verbose_name_plural': 'OFD Interface Paramter',
            },
        ),
    ]
