# Generated by Django 4.2.4 on 2024-11-25 13:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('applications', '0002_application_payment_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('payment_system', models.IntegerField(choices=[(1, 'Dummy'), (2, 'ROBOKASSA'), (3, 'YKASSA')], verbose_name='Payment System')),
                ('payment_dt', models.DateTimeField(blank=True, null=True, verbose_name='Payment Datetime')),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Rejected'), (3, 'Paid'), (4, 'Is refunding'), (5, 'Refuned'), (6, 'Expired')], default=1, verbose_name='Status')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Price')),
                ('currency', models.CharField(choices=[(1, 'Created'), (2, 'Rejected'), (3, 'Paid'), (4, 'Is refunding'), (5, 'Refuned'), (6, 'Expired')], max_length=3, verbose_name='Currency')),
                ('is_subscription', models.BooleanField()),
                ('items_count', models.PositiveIntegerField(default=1, verbose_name='Items Count')),
                ('discount_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Discount Value, %')),
                ('refunding_start_dt', models.DateTimeField(blank=True, null=True, verbose_name='Refunding Request Datetime')),
                ('refund_dt', models.DateTimeField(blank=True, null=True, verbose_name='Refund Datetime')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Refund Amount')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Fee')),
                ('receipt_link', models.URLField(blank=True, null=True, verbose_name='Receipt Url')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('payment_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentitem')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
