# Generated by Django 4.2.4 on 2024-11-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='user_email',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='User Id'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.CharField(default='', max_length=300, verbose_name='User Id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[(1, 'Создано'), (2, 'Отклонено'), (3, 'Оплачено'), (4, 'Возвращается'), (5, 'Возврат'), (6, 'Просрочен')], max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Скидка, %'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Пошлина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество позиций'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата-время оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_system',
            field=models.IntegerField(choices=[(1, 'Dummy'), (2, 'ROBOKASSA'), (3, 'YKASSA')], verbose_name='Платежная система'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receipt_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фиск. чек'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Сумма возврата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата-время возврата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refunding_start_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата-время запроса на возврат'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Создано'), (2, 'Отклонено'), (3, 'Оплачено'), (4, 'Возвращается'), (5, 'Возврат'), (6, 'Просрочен')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
