# Generated by Django 4.2.4 on 2024-11-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_order_options_order_user_email_order_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotent_key',
            field=models.CharField(default='', max_length=300, verbose_name='Idempotent Key'),
        ),
    ]
