# Generated by Django 4.2.4 on 2024-11-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_order_idempotent_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Real Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_system_order_id',
            field=models.CharField(default='', max_length=300, verbose_name='Order Id In Pay System'),
        ),
    ]
