# Generated by Django 4.2.4 on 2024-11-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_order_amount_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Final Price'),
        ),
    ]
