# Generated by Django 4.2.4 on 2024-11-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_order_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_link',
            field=models.CharField(default='', max_length=300, verbose_name='Payment Link'),
        ),
    ]
