# Generated by Django 4.2.4 on 2024-11-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_order_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_system_order_id',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Order Id In Pay System'),
        ),
    ]
