# Generated by Django 4.2.4 on 2024-11-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_subscription_first_order',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='First subscription order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_system_order_id',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='ID заказа в пл.системе'),
        ),
    ]
