# Generated by Django 4.2.4 on 2025-06-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_order_is_subscription_first_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_link',
            field=models.TextField(default='', verbose_name='Payment Link'),
        ),
    ]
