# Generated by Django 4.2.4 on 2025-06-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_order_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Invoice Id'),
        ),
    ]
