# Generated by Django 4.2.4 on 2025-06-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_order_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='crc',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='CRC'),
        ),
    ]
