# Generated by Django 4.2.4 on 2025-07-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_order_crc'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nomenclature',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Nomenclature'),
        ),
    ]
