# Generated by Django 4.2.4 on 2025-07-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_order_nomenclature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='refund_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_dt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refunding_start_dt',
        ),
    ]
