# Generated by Django 4.2.4 on 2025-09-03 10:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_remove_order_refund_amount_remove_order_refund_dt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=250, verbose_name='Expense name')),
                ('expense_date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
