# Generated by Django 4.2.4 on 2026-02-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_id',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='ID чека'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_subscription_first_order',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Первый заказ по подписке'),
        ),
        migrations.AlterField(
            model_name='order',
            name='nomenclature',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Номенклатура'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_system',
            field=models.IntegerField(choices=[(1, 'Dummy'), (2, 'ROBOKASSA'), (3, 'YKASSA'), (4, 'PAYGINE')], verbose_name='Платежная система'),
        ),
    ]
