# Generated by Django 4.2.4 on 2026-03-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Создано'), (2, 'Отклонено'), (3, 'Оплачено'), (4, 'Возвращается'), (5, 'Возврат'), (6, 'Просрочен'), (7, 'Error'), (8, 'Неизвестно'), (9, 'Partially refunded')], default=1, verbose_name='Статус'),
        ),
    ]
