# Generated by Django 4.2.4 on 2026-03-24 07:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0018_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('transaction_id', models.CharField(max_length=50, verbose_name='Transaction ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Refund amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Статус')),
                ('nomenclature', models.JSONField(blank=True, default=None, null=True, verbose_name='Номенклатура')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='billing.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'возврат',
                'verbose_name_plural': 'Возвраты',
                'db_table': 'refunds',
            },
        ),
    ]
