# Generated by Django 4.2.4 on 2026-03-13 07:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0017_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDocument',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('ofd_document_id', models.UUIDField(blank=True, null=True, verbose_name='Идентификатор документа в ОФД')),
                ('ofd_document_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на документ из ОФД')),
                ('status', models.CharField(choices=[('done', 'Done'), ('fail', 'Fail'), ('wait', 'Wait')], default='wait', max_length=10, verbose_name='Статус документа')),
                ('error', models.JSONField(blank=True, null=True, verbose_name='Ошибка')),
                ('request_payload', models.JSONField(verbose_name='Сформированные клиентом данные для запроса ЭФД в ОФД')),
                ('document_type', models.CharField(choices=[('sale', 'Продажа'), ('refund', 'Возврат')], max_length=10, verbose_name='Тип документа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_documents', to='billing.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Фискальный документ',
                'verbose_name_plural': 'Фискальные документы',
                'db_table': 'fiscal_documents',
            },
        ),
    ]
