# Generated by Django 4.2.4 on 2026-03-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscaldocument',
            name='status',
            field=models.CharField(blank=True, choices=[('done', 'Done'), ('fail', 'Fail'), ('wait', 'Wait')], max_length=10, null=True, verbose_name='Статус документа'),
        ),
    ]
