# Generated by Django 4.2.4 on 2026-03-24 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0001_initial'),
        ('billing', '0018_alter_order_status'),
        ('fiscal_documents', '0002_alter_fiscaldocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscaldocument',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_documents', to='refunds.refund', verbose_name='Возврат'),
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_documents', to='billing.order', verbose_name='Заказ'),
        ),
    ]
